on:
  push:
    branches-ignore:
      - 'main'
name: Build and Test on Push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker build
        run: |
          cd front
          ls
          docker build .
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: |
          cd front
          yarn install
      - name: Run test
        run: |
          cd front
          yarn run test
